### ISSUE TITLE
how to get validation metrics

### ISSUE THREAD

**Issue by Greatxcw** [KangLiao929/RecRecNet#2]
Thank you very much for the author's wonderful work, I would like to ask how to get the validation validation metrics, the test code does not provide the part of calculating the validation metrics, can you please provide it?

**Comment by KangLiao929** [comment]
> Thank you very much for the author's wonderful work, I would like to ask how to get the validation validation metrics, the test code does not provide the part of calculating the validation metrics, can you please provide it?

Hi, thanks for your interest. The well-known validation metrics can be calculated by common packages, such as skimage.

**Comment by Greatxcw** [comment]
Thank you！
