### ISSUE TITLE
Supported Datasets

### ISSUE THREAD

**Issue by mldemox** [KangLiao929/RecRecNet#3]
First of all, thank you for your outstanding work. It is well known that a fisheye image is a wide-angle image, is the model suitable for the task of its rectification?

**Comment by KangLiao929** [comment]
> First of all, thank you for your outstanding work. It is well known that a fisheye image is a wide-angle image, is the model suitable for the task of its rectification?

Hi, thanks for your interest. In this work, our aim is to rectangulate the rectified wide-angle image. Namely, the input to our work is the rectification result of wide-angle or fisheye images. For the distortion rectification, you could refer to our other works: https://github.com/KangLiao929/MOWA, https://github.com/uof1745-cmd/PCN.

**Comment by mldemox** [comment]
Thank you for your reply, it seems to me that rectification + rectangling is still a direction to be investigated, and I hope you can make outstanding contributions in that direction in.

**Comment by KangLiao929** [comment]
> Thank you for your reply, it seems to me that rectification + rectangling is still a direction to be investigated, and I hope you can make outstanding contributions in that direction in.

Exactly. The end-to-end framework with rectification + rectangling is an interesting and unexplored direction. A simple baseline can be built based on RecRecNet. I also wish the researchers in this community could make it happen!
